name: Build Wine for Winlator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-arm64:
    name: Build ARM64 Wine for Winlator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison gcc-mingw-w64 \
            g++-aarch64-linux-gnu \
            libx11-dev libfreetype6-dev
      
      - name: Build native Wine tools
        run: |
          # First build the native tools
          mkdir -p wine-tools
          cp -r * wine-tools/ || true
          cd wine-tools
          ./configure --enable-win64
          make -j$(nproc)
          cd ..
      
      - name: Configure for ARM64
        run: |
          ./configure --host=aarch64-w64-mingw32 --with-wine-tools=$PWD/wine-tools --enable-win64 --without-oss --disable-winemenubuilder --disable-tests
      
      - name: Build
        run: make -j$(nproc)
      
      - name: Create artifact
        run: |
          mkdir -p wine-arm64
          cp -r * wine-arm64/ || true
          tar -czf wine-arm64.tar.gz wine-arm64
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wine-arm64
          path: wine-arm64.tar.gz
  
  build-x86_64:
    name: Build x86_64 Wine for Winlator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison gcc-mingw-w64 \
            g++-x86-64-linux-gnu \
            libx11-dev libfreetype6-dev
      
      - name: Build native Wine tools
        run: |
          # First build the native tools
          mkdir -p wine-tools
          cp -r * wine-tools/ || true
          cd wine-tools
          ./configure --enable-win64
          make -j$(nproc)
          cd ..
      
      - name: Configure for x86_64
        run: |
          ./configure --host=x86_64-w64-mingw32 --with-wine-tools=$PWD/wine-tools --enable-win64 --without-oss --disable-winemenubuilder --disable-tests
      
      - name: Build
        run: make -j$(nproc)
      
      - name: Create artifact
        run: |
          mkdir -p wine-x86_64
          cp -r * wine-x86_64/ || true
          tar -czf wine-x86_64.tar.gz wine-x86_64
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wine-x86_64
          path: wine-x86_64.tar.gz 